<script>
	BATinymce.tinymce('{{route('admin.media.tiny.photo.upload')}}',
		'{{route('admin.media.tiny.media.upload')}}',
		'{{route('admin.media.tiny.file.upload')}}',
		'{{csrf_token()}}',
		3000,
		10000,
		5000
	);
</script>